/**
 * Brand Corpus Manager
 *
 * Manage brand voice examples from websites, PDFs, social, and manual entries
 * Provides search, import, and manual entry capabilities
 */

import {
  Search,
  Plus,
  Trash2,
  Globe,
  FileText,
  MessageSquare,
  ExternalLink,
  Loader2,
} from "lucide-react";
import React, { useState, useEffect } from "react";

import { useBrandProfile } from "@/hooks/useBrandProfile";
import type { BrandCorpusChunk } from "@/services/brandService";
import { importBrandSources } from "@/services/functions/brandImport";

// ============================================================================
// TYPES
// ============================================================================

interface BrandCorpusManagerProps {
  clientId: string;
  brandId: string;
}

type AddMode = "manual" | "url" | null;

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export default function BrandCorpusManager({
  clientId,
  brandId,
}: BrandCorpusManagerProps) {
  const {
    corpus,
    loadCorpus,
    addCorpusEntry,
    removeCorpusEntry,
    searchCorpus,
    isLoading,
  } = useBrandProfile(clientId);

  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState<BrandCorpusChunk[]>([]);
  const [addMode, setAddMode] = useState<AddMode>(null);
  const [error, setError] = useState<string | null>(null);

  // Manual entry state
  const [manualTitle, setManualTitle] = useState("");
  const [manualContent, setManualContent] = useState("");
  const [manualSaving, setManualSaving] = useState(false);

  // URL import state
  const [importUrl, setImportUrl] = useState("");
  const [importSourceType, setImportSourceType] = useState<
    "website" | "pdf" | "doc" | "social"
  >("website");
  const [importLoading, setImportLoading] = useState(false);

  // Display corpus or search results
  const displayedCorpus = searchQuery ? searchResults : corpus;

  // ========== HANDLERS ==========

  /**
   * Handle search
   */
  const handleSearch = async () => {
    if (!searchQuery.trim()) {
      setSearchResults([]);
      return;
    }

    try {
      const results = await searchCorpus(searchQuery);
      setSearchResults(results);
    } catch (err) {
      console.error("Search failed:", err);
    }
  };

  /**
   * Handle manual entry save
   */
  const handleManualSave = async () => {
    if (!manualTitle.trim() || !manualContent.trim()) {
      setError("Title and content are required");
      return;
    }

    setManualSaving(true);
    setError(null);

    try {
      await addCorpusEntry({
        source_type: "manual",
        title: manualTitle,
        content: manualContent,
        checksum: "", // Will be generated by hook
        tokens: Math.ceil(manualContent.split(/\s+/).length * 1.3),
      });

      // Reset form
      setManualTitle("");
      setManualContent("");
      setAddMode(null);
      await loadCorpus();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save entry");
    } finally {
      setManualSaving(false);
    }
  };

  /**
   * Handle URL import
   */
  const handleUrlImport = async () => {
    if (!importUrl.trim()) {
      setError("URL is required");
      return;
    }

    setImportLoading(true);
    setError(null);

    try {
      const result = await importBrandSources({
        client_id: clientId,
        brand_id: brandId,
        sources: [
          {
            source_type: importSourceType,
            url: importUrl,
          },
        ],
      });

      if (result.ok) {
        // Reset form
        setImportUrl("");
        setAddMode(null);
        await loadCorpus();
      } else {
        setError("Import failed. Check URL and try again.");
      }
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to import from URL",
      );
    } finally {
      setImportLoading(false);
    }
  };

  /**
   * Handle delete
   */
  const handleDelete = async (id: string) => {
    if (!confirm("Are you sure you want to delete this corpus entry?")) return;

    try {
      await removeCorpusEntry(id);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete entry");
    }
  };

  // ========== EFFECTS ==========

  // Trigger search when query changes (debounced)
  useEffect(() => {
    const timer = setTimeout(() => {
      if (searchQuery) {
        void handleSearch();
      } else {
        setSearchResults([]);
      }
    }, 300);

    return () => clearTimeout(timer);
  }, [searchQuery, handleSearch]);

  // ========== RENDER ==========

  return (
    <div className="space-y-6">
      {/* Header with Search */}
      <div className="flex items-center gap-4">
        <div className="flex-1 relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search corpus..."
            className="w-full pl-10 pr-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
          />
        </div>

        <button
          onClick={() => setAddMode(addMode ? null : "manual")}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
        >
          <Plus className="w-4 h-4" />
          Add Entry
        </button>
      </div>

      {/* Error Message */}
      {error && (
        <div className="p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
          <p className="text-sm text-red-800 dark:text-red-200">{error}</p>
        </div>
      )}

      {/* Add Mode Toggle */}
      {addMode && (
        <div className="p-4 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg">
          <div className="flex gap-2 mb-4">
            <button
              onClick={() => setAddMode("manual")}
              className={`px-4 py-2 rounded-lg transition-colors ${
                addMode === "manual"
                  ? "bg-indigo-600 text-white"
                  : "bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-300 dark:hover:bg-gray-600"
              }`}
            >
              <MessageSquare className="inline w-4 h-4 mr-2" />
              Manual Entry
            </button>
            <button
              onClick={() => setAddMode("url")}
              className={`px-4 py-2 rounded-lg transition-colors ${
                addMode === "url"
                  ? "bg-indigo-600 text-white"
                  : "bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-300 dark:hover:bg-gray-600"
              }`}
            >
              <Globe className="inline w-4 h-4 mr-2" />
              Import from URL
            </button>
          </div>

          {/* Manual Entry Form */}
          {addMode === "manual" && (
            <div className="space-y-3">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Title
                </label>
                <input
                  type="text"
                  value={manualTitle}
                  onChange={(e) => setManualTitle(e.target.value)}
                  placeholder="e.g., Newsletter Excerpt, Social Post, Annual Report"
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Content
                </label>
                <textarea
                  value={manualContent}
                  onChange={(e) => setManualContent(e.target.value)}
                  placeholder="Paste text from your newsletter, social media, website, or other brand materials..."
                  rows={8}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-transparent font-mono text-sm"
                />
                <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                  {manualContent.split(/\s+/).length} words
                </p>
              </div>

              <div className="flex gap-2">
                <button
                  onClick={handleManualSave}
                  disabled={
                    manualSaving || !manualTitle.trim() || !manualContent.trim()
                  }
                  className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  {manualSaving ? (
                    <>
                      <Loader2 className="inline w-4 h-4 mr-2 animate-spin" />
                      Saving...
                    </>
                  ) : (
                    "Save Entry"
                  )}
                </button>
                <button
                  onClick={() => {
                    setAddMode(null);
                    setManualTitle("");
                    setManualContent("");
                    setError(null);
                  }}
                  className="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}

          {/* URL Import Form */}
          {addMode === "url" && (
            <div className="space-y-3">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Source Type
                </label>
                <select
                  value={importSourceType}
                  onChange={(e) =>
                    setImportSourceType(
                      e.target.value as typeof importSourceType,
                    )
                  }
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                >
                  <option value="website">Website</option>
                  <option value="pdf">PDF Document</option>
                  <option value="doc">Document</option>
                  <option value="social">Social Media</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  URL
                </label>
                <input
                  type="url"
                  value={importUrl}
                  onChange={(e) => setImportUrl(e.target.value)}
                  placeholder="https://example.org/about"
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                />
                <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                  Content will be fetched and processed automatically
                </p>
              </div>

              <div className="flex gap-2">
                <button
                  onClick={handleUrlImport}
                  disabled={importLoading || !importUrl.trim()}
                  className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  {importLoading ? (
                    <>
                      <Loader2 className="inline w-4 h-4 mr-2 animate-spin" />
                      Importing...
                    </>
                  ) : (
                    "Import"
                  )}
                </button>
                <button
                  onClick={() => {
                    setAddMode(null);
                    setImportUrl("");
                    setError(null);
                  }}
                  className="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Corpus Table */}
      <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
              <tr>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                  Source
                </th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                  Title
                </th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                  Type
                </th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                  Tokens
                </th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                  Date
                </th>
                <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
              {displayedCorpus.length === 0 && !isLoading && (
                <tr>
                  <td
                    colSpan={6}
                    className="px-4 py-8 text-center text-gray-500 dark:text-gray-400"
                  >
                    {searchQuery
                      ? "No results found. Try a different search term."
                      : "No corpus entries yet. Add your first brand voice example above."}
                  </td>
                </tr>
              )}

              {displayedCorpus.map((chunk) => (
                <tr
                  key={chunk.id}
                  className="hover:bg-gray-50 dark:hover:bg-gray-900/50"
                >
                  <td className="px-4 py-3">
                    {chunk.source_url ? (
                      <a
                        href={chunk.source_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center gap-1 text-indigo-600 dark:text-indigo-400 hover:underline"
                      >
                        <ExternalLink className="w-3 h-3" />
                        <span className="text-sm truncate max-w-xs">
                          {chunk.source_url}
                        </span>
                      </a>
                    ) : (
                      <span className="text-sm text-gray-500 dark:text-gray-400">
                        Manual entry
                      </span>
                    )}
                  </td>
                  <td className="px-4 py-3">
                    <span className="text-sm text-gray-900 dark:text-white">
                      {chunk.title || "Untitled"}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300">
                      {chunk.source_type === "website" && (
                        <Globe className="w-3 h-3 mr-1" />
                      )}
                      {chunk.source_type === "pdf" && (
                        <FileText className="w-3 h-3 mr-1" />
                      )}
                      {chunk.source_type === "manual" && (
                        <MessageSquare className="w-3 h-3 mr-1" />
                      )}
                      {chunk.source_type}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <span className="text-sm text-gray-600 dark:text-gray-400">
                      {chunk.tokens?.toLocaleString() || "—"}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <span className="text-sm text-gray-600 dark:text-gray-400">
                      {new Date(chunk.updated_at).toLocaleDateString()}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <button
                      onClick={() => handleDelete(chunk.id)}
                      className="inline-flex items-center gap-1 px-3 py-1 text-sm text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 rounded transition-colors"
                    >
                      <Trash2 className="w-3 h-3" />
                      Delete
                    </button>
                  </td>
                </tr>
              ))}

              {isLoading && (
                <tr>
                  <td colSpan={6} className="px-4 py-8 text-center">
                    <Loader2 className="w-6 h-6 mx-auto animate-spin text-indigo-600" />
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Stats */}
      <div className="flex items-center justify-between text-sm text-gray-600 dark:text-gray-400">
        <div>
          {searchQuery ? (
            <>
              Showing {searchResults.length} of {corpus.length} entries
            </>
          ) : (
            <>{corpus.length} corpus entries total</>
          )}
        </div>
        <div>
          {corpus.reduce((sum, c) => sum + (c.tokens || 0), 0).toLocaleString()}{" "}
          tokens total
        </div>
      </div>
    </div>
  );
}
